# Generated by Django 2.2.7 on 2020-11-11 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('userID', models.BigIntegerField()),
                ('ORCid', models.BigIntegerField()),
                ('scopusID', models.BigIntegerField()),
                ('bio', models.CharField(max_length=1000)),
                ('affiliation', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phoneno', models.BigIntegerField(blank=True, null=True)),
                ('weblinks', models.URLField()),
                ('designation', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('clgID', models.BigIntegerField()),
                ('website', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('title', models.CharField(max_length=100)),
                ('DOI', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('pri_author', models.CharField(max_length=100)),
                ('citation', models.IntegerField()),
                ('fields', models.CharField(max_length=100)),
                ('publication_date', models.TimeField()),
                ('publish_name', models.CharField(max_length=100)),
                ('abstract', models.CharField(max_length=1000)),
                ('authorID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_app.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('deptID', models.BigIntegerField()),
                ('collegeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.College')),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='deptartment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_app.Department'),
        ),
        migrations.AddField(
            model_name='author',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
