# Generated by Django 3.0.6 on 2020-11-12 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0003_author_college'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paper',
            old_name='publish_name',
            new_name='publisher_name',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='pri_author',
        ),
        migrations.AddField(
            model_name='paper',
            name='co_author',
            field=models.CharField(default=None, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paper',
            name='abstract',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='paper',
            name='publication_date',
            field=models.DateTimeField(),
        ),
    ]
