# Generated by Django 2.2.7 on 2020-11-12 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0004_auto_20201112_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='authorID',
        ),
    ]
