# Generated by Django 3.0.6 on 2020-11-23 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0006_auto_20201123_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
